name: my_pokemon_list
description: Pokemon list app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  go_router: ^10.0.0 
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  skeletonizer: ^0.7.0
  

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
